#!

# CAL file is generated by calibrate.py
# use the CAL file if there is one, otherwise the CSV file from spectralAverage.py
SPECTRUM="${1%.*}.cal"
if [[ ! -f $SPECTRUM ]]; then SPECTRUM="${1%.*}.csv"; fi
if [[ ! -f $SPECTRUM ]]; then echo Spectrum file $SPECTRUM not found; exit 1; fi

C436=$(awk -F ',' '{print $3;exit}' "$SPECTRUM")
C611=$(awk -F ',' '{print $4;exit}' "$SPECTRUM")
SNAME=$(awk -F ',' '{print $5;exit}' "$SPECTRUM")
SDESC=$(awk -F ',' '{print $6;exit}' "$SPECTRUM")

export NO_AT_BRIDGE=1

gnuplot <<EOF

width = 1280                        # size of background image
height = 720
set term qt size width,height

set datafile separator ","

set ylabel 'Intensity'
#set ytics nomirror
set grid ytics lw 2
set xlabel 'nm'

set title "$SDESC"

m = (611.0 - 436.0) / ($C611 - $C436)
b = 611.0 - m * $C611

set xrange [b+1:]
set yrange [0:]

set style arrow 1 nohead front dashtype 3

set arrow from 405,0 to 405,graph 1 as 1
set label "Hg405" at 405,5
set arrow from 436,0 to 436,graph 1 as 1
set label "Hg436" at 436,5
set arrow from 487,0 to 487,graph 1 as 1
set label "Tb487" at 487,5
set arrow from 542,0 to 542,graph 1 as 1
set arrow from 546,0 to 546,graph 1 as 1
set label "Hg546" at 546,5
#set arrow from 577,0 to 577,graph 1 as 1
#set arrow from 580,0 to 580,graph 1 as 1
#set arrow from 584,0 to 584,graph 1 as 1
#set arrow from 587,0 to 587,graph 1 as 1
#set arrow from 593,0 to 593,graph 1 as 1
#set arrow from 599,0 to 599,graph 1 as 1
set arrow from 611,0 to 611,graph 1 as 1
set label "Eu611" at 611,5

plot "$SPECTRUM" using (\$1*m+b):2 title "$SNAME" with lines

pause mouse button2 "button2 to exit"

EOF